### ISSUE TITLE
Is it possible to not match multiple directories  --not-match-d

### ISSUE THREAD

**Issue by kteb** [hhatto/gocloc#11]
Hello, it's a nice project, I wanted to know if there was a way to exclude more than one folder ?

If yes, how ? If no, will it be a big change to implement ?

**Comment by rpalmer245** [comment]
TO match multiple directories, use regular expressions.  So you would separate directory names with a pipe character: |.

Depending on your shell, you may need to escape the pipe character with a backslash.

Example: gocloc . --not-match-d=vendor\|.docker
This would exclude .docker and vendor directories from gocloc's results.

**Comment by kteb** [comment]
It worked thanks
