### ISSUE TITLE
go get instructions fail

### ISSUE THREAD

**Issue by MMulthaupt** [hhatto/gocloc#24]
`go get` complains trying to get `gocloc`.
```
~$ go get -u github.com/hhatto/gocloc/cmd/gocloc
package github.com/src-d/enry: code in directory /home/martin/go/src/github.com/src-d/enry expects import "github.com/src-d/enry/v2"
```
Not sure what it means for code to "expect" an import and why that is a problem.

**Comment by hhatto** [comment]
#23 same problem?

**Comment by MMulthaupt** [comment]
Yeah that fixes it. Please update the README.
```
GO111MODULE=on go get -u github.com/hhatto/gocloc/cmd/gocloc
```

**Comment by hhatto** [comment]
update https://github.com/hhatto/gocloc/commit/a79a46671038e0d6b951ce245f1edebf11915a00
