### ISSUE TITLE
Installation failure on Windows

### ISSUE THREAD

**Issue by acsbendi** [hhatto/gocloc#32]
When I tried to install it on Windows without Go modules, I encountered the problem that is also mentioned in the repo's README (`package github.com/src-d/enry: code in directory /PATH/TO/go/src/github.com/src-d/enry expects import "github.com/src-d/enry/v2"`). 

However, I could not install it using Go modules either. The error message is the following: `go: cannot find main module; see 'go help modules'`.

**Comment by hhatto** [comment]
@acsbendi 
sorry for late reply.

I was able to install it successfully in my environment.
Do you still have the same problem with the latest source code?

install and build log on my environment (Windows 10 Home / amd64):
```
PS C:\Users\hhatt\Documents\GitHub\hhatto\gocloc> go build -o ./bin/gocloc.exe cmd/gocloc/main.go
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/go-enry/go-enry/v2 v2.6.0

PS C:\Users\hhatt\Documents\GitHub\hhatto\gocloc> .\bin\gocloc.exe .
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              15            259            129           1778
Markdown                         1             25              0            172
YAML                             1              0              0             28
Makefile                         1              5              0             13
-------------------------------------------------------------------------------
TOTAL                           18            289            129           1991
-------------------------------------------------------------------------------
PS C:\Users\hhatt\Documents\GitHub\hhatto\gocloc>
```

**Comment by acsbendi** [comment]
I've checked it again, and the build/install succeeds now, so I'll close this issue.
