### ISSUE TITLE
Unable to install in windows 7

### ISSUE THREAD

**Issue by ajpen** [hhatto/gocloc#4]
I'm trying to install for windows and I'm getting the following error:

    $ go get github.com/hhatto/gocloc
    # github.com/hhatto/gocloc
    ..\..\..\..\go_workspace\src\github.com\hhatto\gocloc\file.go:53: scanner.Buffer undefined (type *bufio.Scanner has no field or method Buffer)

Go version = go1.5.1 windows/amd64

**Comment by hhatto** [comment]
gocloc requires Go1.6++
