### ISSUE TITLE
Question: how it works when use command "gocloc ."

### ISSUE THREAD

**Issue by Xieyuschen** [hhatto/gocloc#41]
It's quite useful to calculate how many codes are there in my project. After using it I try to implement a more simple one with a few same project to play. However something disturbed me a lot so I hope some one can help me. My question is how the command `gocloc .` call function to calculate lines of code.
I knew that `go get <this project address>` download the package so I can use it in my project. But why `gocloc .` can invoke this package? What I know is only pass this argument with `main args` as `go run main.go gocloc .`.
How this [main function](https://github.com/hhatto/gocloc/blob/4391fc122d9ec4f29305a088ae91d6efffea5b5d/cmd/gocloc/main.go#L195) get the command info input at the terminal?

**Comment by hhatto** [comment]
usage

```
$ go get -u github.com/hhatto/gocloc/cmd/gocloc
```
install your gopath (bin path).

**Comment by Xieyuschen** [comment]
Thank you for your help, I have got it:)
