### ISSUE TITLE
proposal:  Split into a command and a library

### ISSUE THREAD

**Issue by nemith** [hhatto/gocloc#6]
I would like to write some code to analyze a repository and write the stats into a backend time relational database and having the analysis from gocloc would be nice, but to write some custom code around it I would need it to be importable.

I could fork but what do you think about creating a go package and  separate cmd?

**Comment by hhatto** [comment]
@nemith 

Thanks for suggesition 👍 

I tried to separate, go package and command tool.

install for command line :
```
go get -u github.com/hhatto/gocloc/cmd/gocloc
```

install for go package
```
go get -u github.com/hhatto/gocloc
```

sample code for go package
https://github.com/hhatto/gocloc/blob/259fe0ac4b12010a9dd69a4770506c87217d3a03/examples/files.go

How about this?

**Comment by nemith** [comment]
Thank you!
