### ISSUE TITLE
0.5.1 release was not completed?

### ISSUE THREAD

**Issue by chenrui333** [hhatto/gocloc#72]
👋 it looks like 0.5.1 release was not completed, see [this failed action run](https://github.com/hhatto/gocloc/actions/runs/5651887622/job/15310688780).  Create this issue to raise some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/137486

**Comment by hhatto** [comment]
@chenrui333 
The configuration file for goreleaser was outdated, which caused the GitHub Actions for the v0.5.1 binary release to fail.
I have just corrected the goreleaser configuration file and re-released v0.5.1.

**Comment by chenrui333** [comment]
thanks @hhatto let me check on the homebrew pr again.
